from pathlib import Path
p=Path('app/src/main/java/com/differentfreelancer/model3d/MainActivity.java')
s=p.read_text(encoding='utf-8')
if 'PROJECT_SAF_URI_V17' in s:
    print('Project SAF URI v17 already applied'); raise SystemExit(0)
old='''    private Uri findChild(Uri tree,String name)throws Exception{Uri children=DocumentsContract.buildChildDocumentsUriUsingTree(tree,DocumentsContract.getTreeDocumentId(tree));try(Cursor c=getContentResolver().query(children,new String[]{DocumentsContract.Document.COLUMN_DOCUMENT_ID,DocumentsContract.Document.COLUMN_DISPLAY_NAME},null,null,null)){if(c!=null)while(c.moveToNext())if(name.equals(c.getString(1)))return DocumentsContract.buildDocumentUriUsingTree(tree,c.getString(0));}return null;}\n    private Uri ensureProjectDir(Uri tree,String project)throws Exception{String name=safeName(project);Uri dir=findChild(tree,name);if(dir!=null)return dir;return DocumentsContract.createDocument(getContentResolver(),tree,DocumentsContract.Document.MIME_TYPE_DIR,name);}\n    private Uri upsertFile(Uri dir,String name,String mime)throws Exception{Uri file=findChild(dir,name);if(file!=null)return file;return DocumentsContract.createDocument(getContentResolver(),dir,mime,name);}\n'''
new='''    // PROJECT_SAF_URI_V17\n    // ACTION_OPEN_DOCUMENT_TREE returns a tree URI. DocumentsContract.createDocument()\n    // requires a document URI, and child queries require the CURRENT document id rather\n    // than always using the tree root id. Mixing those URI forms caused\n    // IllegalArgumentException: Invalid URI on ExternalStorageProvider.\n    private Uri treeRootDocument(Uri tree)throws Exception{\n        if(tree==null)throw new Exception("Folder project belum dipilih");\n        String rootId=DocumentsContract.getTreeDocumentId(tree);\n        return DocumentsContract.buildDocumentUriUsingTree(tree,rootId);\n    }\n    private String currentDocumentId(Uri uri)throws Exception{\n        if(uri==null)throw new Exception("URI folder project kosong");\n        try{return DocumentsContract.getDocumentId(uri);}\n        catch(Exception ignored){return DocumentsContract.getTreeDocumentId(uri);}\n    }\n    private Uri findChild(Uri parent,String name)throws Exception{\n        String parentId=currentDocumentId(parent);\n        Uri children=DocumentsContract.buildChildDocumentsUriUsingTree(parent,parentId);\n        try(Cursor c=getContentResolver().query(children,new String[]{DocumentsContract.Document.COLUMN_DOCUMENT_ID,DocumentsContract.Document.COLUMN_DISPLAY_NAME},null,null,null)){\n            if(c!=null)while(c.moveToNext()){\n                if(name.equals(c.getString(1)))return DocumentsContract.buildDocumentUriUsingTree(parent,c.getString(0));\n            }\n        }\n        return null;\n    }\n    private Uri ensureProjectDir(Uri tree,String project)throws Exception{\n        Uri rootDoc=treeRootDocument(tree);\n        String name=safeName(project);\n        Uri dir=findChild(rootDoc,name);\n        if(dir!=null)return dir;\n        Uri created=DocumentsContract.createDocument(getContentResolver(),rootDoc,DocumentsContract.Document.MIME_TYPE_DIR,name);\n        if(created==null)throw new Exception("Folder project gagal dibuat");\n        return created;\n    }\n    private Uri upsertFile(Uri dir,String name,String mime)throws Exception{\n        Uri file=findChild(dir,name);\n        if(file!=null)return file;\n        Uri created=DocumentsContract.createDocument(getContentResolver(),dir,mime,name);\n        if(created==null)throw new Exception(name+" gagal dibuat");\n        return created;\n    }\n    private OutputStream openProjectOutput(Uri file)throws Exception{\n        OutputStream out=null;\n        try{out=getContentResolver().openOutputStream(file,"rwt");}catch(Exception ignored){}\n        if(out==null)try{out=getContentResolver().openOutputStream(file,"wt");}catch(Exception ignored){}\n        if(out==null)out=getContentResolver().openOutputStream(file,"w");\n        if(out==null)throw new Exception("Output project tidak tersedia");\n        return out;\n    }\n'''
if old not in s: raise SystemExit('Old SAF helper block not found')
s=s.replace(old,new,1)
old2='''try(OutputStream out=getContentResolver().openOutputStream(file,"rwt")){if(out==null)throw new Exception("Output tidak tersedia");out.write(json.getBytes(StandardCharsets.UTF_8));out.flush();}'''
new2='''try(OutputStream out=openProjectOutput(file)){out.write(json.getBytes(StandardCharsets.UTF_8));out.flush();}'''
if old2 not in s: raise SystemExit('Old project output block not found')
s=s.replace(old2,new2,1)
p.write_text(s,encoding='utf-8')
print('Project SAF URI v17 applied')
